name = "repaymentguide"
compatibility_date = "2024-01-01"

[env.production]
routes = [
  { pattern = "/_next/static/(.*)", type = "Static" },
  { pattern = "/images/(.*)", type = "Static" },
  { pattern = "/favicon.ico", type = "Static" },
  { pattern = "/robots.txt", type = "Static" },
  { pattern = "/sitemap.xml", type = "Static" },
  { pattern = "(.*)", type = "Static" },
]
